#%RAML 1.0
title: EventedAPI_Consumer_Web
version: 1.0

uses:
  data_types:  libraries/EventedAPI_DataTypes.raml
  annotation_types: libraries/EventedAPI_Annotations.raml
  events:  libraries/event_library/EventLibrary.raml

/EventConsumer:
  description: Event Producer 
  (annotation_types.domain):  "IoT_Mining"
  (annotation_types.channel_id):  "12345"
  (annotation_types.subject_id):  "789"
  (annotation_types.consumer_id):  "1222222"
  (annotation_types.provider_channel_url):  "http://event_provider_banking.cloudhub.io/"
        
  get:
    description: Post an Event
    queryParameters:
      channel_id: 
        type:  string
        example:  "1234"
      subject_id:  
        type:  string
        example:  "5678"
      channel_url:  
        type: string
        example: "http://event_provider_banking.cloudhub.io/"
      
    body: 
      application/json:
        type: events.ValidEvent
        example:  !include samples/event_type_post.json
  post:
    description: Subscriber to Events on this Subject by providing a URL to receive Events on.
    queryParameters:
      channel_id: 
        type:  string
        example:  "1234"
      subject_id:  
        type:  string
        example:  "5678"
      channel_url:  
        type: string
        example: "http://event_provider_banking.cloudhub.io/"
    body: 
      application/json:
        type: data_types.EventSubscription
    
      
        
         